-  name: Add Docker repo
   get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/docker-ce.repo
-  debug:
       msg: "hello {{ansible_distribution_version|int}}"

-  name: Install Docker-ce
   yum: name=docker-ce state=latest
   when: ansible_distribution_version|int < 8

-  name: Install Docker
   yum: name=docker-ce state=latest
   when: ansible_distribution_version|int >= 8

-  name: Add user to docker group
   user:
     name: "{{ ansible_user }}"
     group: docker
   when: ansible_distribution_version|int < 8

-  name: Install Docker Compose
   get_url:
     url: "{{ docker_compose_url }}"
     dest: "{{ docker_compose_path }}"
     mode: 0755


-  name: Install packages
   package:
     name: "{{ item }}"
     state: present
   with_items:
     - "epel-release" #TODO var list
     - "certbot"
     #- "python-certbot-apache"
     - "vim"
     - "git"
     - "wget"
     - "firewalld"


- name: Open Server ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    zone: public
  with_items:
    - 80/tcp
    - 443/tcp
